### ISSUE TITLE
Auto closing br (<br />) seems not recognized

### ISSUE THREAD

**Issue by scorsi** [benwinding/quill-html-edit-button#23]
Hello,

I have the following value:
```html
<p> Avec la crise sanitaire du COVID-19, les personnes fragilisées sont de plus en plus nombreuses en France. On l’observe notamment dans les grandes villes comme Paris, Lille, Bordeaux, Marseille, Nantes, ou encore Strasbourg. </p> <br /> <p> Les équipes de l’Ordre de Malte France sont présentes quotidiennement dans des actions de terrain par le biais de maraudes alimentaires et médicales, p’tits déjeuners solidaires ou via des actions de secours pour aider concrètement les personnes les plus fragiles. Vous souhaitez financer des projets près de chez vous ? Découvrez les initiatives Les Défis Malte. </p> <br />
```

When passed to `quill-html-edit-button` lib I got the following:
```html
<p>
  Avec la crise sanitaire du COVID-19, les personnes fragilisées sont de plus en plus nombreuses en France. On l’observe notamment dans les grandes villes comme Paris, Lille, Bordeaux, Marseille, Nantes, ou encore Strasbourg.
</p>
<p>
</p>
<p>
  Les équipes de l’Ordre de Malte France sont présentes quotidiennement dans des actions de terrain par le biais de maraudes alimentaires et médicales, p’tits déjeuners solidaires ou via des actions de secours pour aider concrètement les personnes les plus fragiles. Vous souhaitez financer des projets près de chez vous ? Découvrez les initiatives Les Défis Malte.
</p>
```
The `<br />` in the middle has been transformed to `<p></p>` and the last one did disappear.

Do you have any idea ? Is it possible to be a bug ?

Thanks :)

**Comment by benwinding** [comment]
Hi @scorsi, 
This module `quill-html-edit-button` only passes the raw HTML string to Quill, so it's not this module that is changing the `<br>` tag. 
There's no way to easily fix this unfortunately, due to the following problems:
- The browser has rules on how the [content-editable](https://www.w3schools.com/tags/att_global_contenteditable.asp) div behaves (which is what Quill's input area uses)
- Quill also does some things to `<br>` tags as shown in [this issue here](https://github.com/quilljs/quill/issues/1328)
I could be mistaken though, Let me know if there's anything else,
Ben

**Comment by benwinding** [comment]
Closing for now as it seems to be a [quill issue](https://github.com/quilljs/quill/issues/1328)

**Comment by scorsi** [comment]
Yes of course ! Thanks for your answer ! :)
