### ISSUE TITLE
I can't write anything inside the html box

### ISSUE THREAD

**Issue by boyprivate0** [benwinding/quill-html-edit-button#38]
I'm using quill-html-edit-button version **1.0.12** 
The issue is that I can't write anything inside the box,

I tried to use the version 1.0.13 upto the latest one, but it keep on throwing 
`ReferenceError: Quill is not defined`

I tried window.Quill = Quill;
but that say's 
`Property Quill doesn't exist on type window `

I'm integrating it inside Angular app.
![image](https://user-images.githubusercontent.com/29142805/103910470-ae4fbb00-5126-11eb-9bd0-881e86b9d1e4.png)

**Comment by benwinding** [comment]
Can you check the following:
- Are you using `ngx-quill`?
- Have you added `quill.min.js` to `angular.json`?

Also, some more example code, and error messages will help me with your issue.

Cheers,
Ben

**Comment by boyprivate0** [comment]
package.json 
`ngx-quill": "^1.6.0"`
`"quill-html-edit-button": "^1.0.12"`
Angular version is 4.0.2

We have ".angular-cli.json" file and yes I've added it inside scripts tag
`"../node_modules/quill-html-edit-button/dist/quill.htmlEditButton.min.js"`

The pop-up appears but can't write/edit anything inside that.

**Comment by si-lang** [comment]
@boyprivate0 You can try to follow [this StackOverflow post](https://stackoverflow.com/questions/58701585/how-do-i-fix-this-error-i-get-whenever-i-try-to-register-quill-better-table-with) until and including step 3, which worked for me just fine.
Instead of using quill-better-table you of course use htmlEditButton and the config object would be for you your MODULES object wrapped in an object with the modules property.
